apiVersion: apps/v1
kind: Deployment
metadata:
  name: limited-resources-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: limited-resources
  template:
    metadata:
      labels:
        app: limited-resources
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"