apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-initdb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/kubernetes/mysql_db   # Update this path
    type: DirectoryOrCreate