apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Note: These are base64 encoded values
  MYSQL_ROOT_PASSWORD: c3VzaGFuMDE=      # sushan01
  MYSQL_USER: bW9ja3Vw                  # mockup
  MYSQL_PASSWORD: TW9ja3VwQDEyMw==         # Mockup@123