apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-scripts
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS myapp;
    USE myapp;
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL
    );