# Service (LoadBalancer) for Java Mockup App
apiVersion: v1
kind: Service
metadata:
  name: mockup-app-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 4567
    protocol: TCP
  selector:
    app: mockup-app